version: "3.8"

services:
  mc-server:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    restart: unless-stopped

    ports:
      - "25565:25565"

    volumes:
      - /opt/minecraft/data:/data

    environment:
      EULA: "TRUE"

      # отключаем Mojang auth (если нужно)
      ONLINE_MODE: "false"

      # используем свой jar
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "/data/server.jar"

      # настройки сервера
      MEMORY: "4G"
      MOTD: "Minecraft Cluster 1.21.4"

      # запрет скачивания defaults
      SKIP_DOWNLOAD_DEFAULTS: "true"

      # принять eula автоматически
      OVERRIDE_SERVER_PROPERTIES: "true"

    stdin_open: true
    tty: true
