version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    restart: unless-stopped
    ports:
      - "25565:25565"          # порт Minecraft
    environment:
      EULA: "TRUE"             # обязательно
      TYPE: "VANILLA"          # или PAPER, FABRIC, FORGE, NEOFORGE и т.д.
      VERSION: "latest"
      MEMORY: "4G"             # сколько RAM выделить
      SERVER_NAME: "My Awesome Server"
      MOTD: "§aДобро пожаловать! §r§7Играем с друзьями"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "strongpassword123"
      # WHITELIST: "player1,player2"
      # OPS: "player1"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true