name: Deploy Minecraft Cluster

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          command -v wget >/dev/null 2>&1 || sudo apt-get update && sudo apt-get install -y wget unzip

          wget https://hashicorp-releases.yandexcloud.net/terraform/1.14.0/terraform_1.14.0_linux_amd64.zip
          sudo unzip -o terraform_1.14.0_linux_amd64.zip -d /usr/local/bin/
          rm terraform_1.14.0_linux_amd64.zip

          terraform version

      - name: Configure Terraform Mirror
        run: |
          cat <<EOF > ~/.terraformrc
          provider_installation {
            network_mirror {
              url = "https://terraform-mirror.mcs.mail.ru"
              include = ["registry.terraform.io/*/*"]
            }
            direct {
              exclude = ["registry.terraform.io/*/*"]
            }
          }
          EOF

      - name: Terraform Init
        run: terraform init


      - name: Remove old terraform state if exists
        run: terraform state rm openstack_networking_secgroup_rule_v2.minecraft || true

      - name: Import existing minecraft security rule
        run: |
          RULE_ID=$(openstack security group rule list minecraft-sg -f value -c ID | head -n 1)
          terraform import openstack_networking_secgroup_rule_v2.minecraft $RULE_ID || true

      
          
      #- name: Import existing minecraft security rule
      #  run: |
      #    terraform import \
      #   openstack_networking_secgroup_rule_v2.minecraft \
      #    3a60ee9a-6d1e-46a1-8f27-0402db5a167c || true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
