name: Deploy Minecraft Cluster

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.8"

      - name: Prepare Terraform Lock
        # Удаляем старый файл блокировки, который мешает инициализации на Linux
        run: rm -f .terraform.lock.hcl

      - name: Terraform Init
        # Флаг -upgrade скачает свежие версии провайдеров прямо на раннере
        run: terraform init -upgrade
        env:
          TF_VAR_password: ${{ secrets.TF_VAR_password }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_password: ${{ secrets.TF_VAR_password }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          TF_VAR_password: ${{ secrets.TF_VAR_password }}